builder:
  track: dev

labels:
  app-group: estafette-ci
  team: estafette-team
  language: nodejs

version:
  semver:
    major: 0
    minor: 1

stages:
  audit-and-restore:
    parallelStages:
      audit:
        image: extensions/npm-audit:dev
        action: audit
        workspace: estafette
        channels:
        - '#npm-audit'

      restore:
        image: node:13.6.0-alpine
        commands:
        - npm ci

  lint:
    image: node:13.6.0-alpine
    commands:
    - npm run lint

  build:
    image: node:13.6.0-alpine
    commands:
    - npm run build

  bake:
    image: extensions/docker:dev
    action: build
    repositories:
    - estafette
    path: ./dist
    copy:
    - favicon.ico
    - nginx.vh.default.conf
    - docker-entrypoint.sh
    - package-lock.json

  check-container:
    parallelStages:
      check-efficiency:
        image: extensions/docker:dev
        action: dive
        repositories:
        - estafette

      vulnerability-scan:
        image: extensions/docker:dev
        action: trivy
        repositories:
        - estafette

  test:
    services:
    - name: ci.estafette.io
      image: estafette/estafette-ci-web:${ESTAFETTE_BUILD_VERSION}
      readiness:
        path: /robots.txt
        port: 5000

    image: node:13.6.0-alpine
    commands:
    - apk add curl
    - curl --fail http://ci.estafette.io:5000/manifest/encrypt

  push-to-docker-hub:
    image: extensions/docker:dev
    retries: 5
    action: push
    repositories:
    - estafette

  slack-notify:
    image: extensions/slack-build-status:dev
    workspace: estafette
    channels:
    - '#build-status'
    when:
      status == 'succeeded' ||
      status == 'failed'

releases:
  tooling-estafette:
    clone: true
    stages:
      deploy:
        image: extensions/gke:dev
        namespace: estafette-ci
        visibility: iap
        iapOauthClientID: estafette.secret(iXOTyaK0CMquct2i.gHSRFMIopefYNe0bG4fANPaRaBknLwPP4qa1KiIUR_UWW6ORO5n9rLKvKGeRg5U_c_D3gQipezDEzmfaO7jsLbk8f8GpV4JFqMy3hT8g0dkdr5ndOkAwblORXBvK482HY7ihEWhEuRtyzGpK9YGALA==.qUmsBfkw3v36MosJJrfGZ9-yc09RHUjB55e4bAw5KPscGJ6eOLv-GTDQmVvuPK1x5NyJqrc=)
        iapOauthClientSecret: estafette.secret(UwPXjVCad4ycIYJK.SSTHl16_SNYh4p0JB5o-nDdAnhQM3gKLgLmapXhj4fGQT0zgkQMLP-TVp18jyWFW.YxXxmUntMPgvyMI_JtxuzB18qEBw_gnOhImTolZTnuDveWlHDvG5nrmRJnjMd5xb1coCBsw=)
        container:
          repository: estafette
          cpu:
            request: 10m
            limit: 200m
          memory:
            request: 15Mi
            limit: 512Mi
          liveness:
            path: /robots.txt
          readiness:
            path: /robots.txt
          metrics:
            scrape: false
        hosts:
        - estafette.secret(z6C9Piz4EhMxWMc8.uxcITmg39HiLJuuqSyPRM06PTWNd6S1x1QxfYYeyGoBLcgkM)
        - estafette.secret(Yckgy_NXzit9gA2t.l8LZcWPZbKkf5fMydVx6beetqZ_5sINemOrovXxfv0IbUmETD2TE.ldjZeHDeNr4Vpb8-KFxpavSwpdS1up1EbF1RNaa5S0SJ23IeCp9OQWfCjvf-ceIgFv8pwyg=)
        chaosproof: true
        manifests:
          files:
          - gke/ingress.yaml

      slack-notify:
        image: extensions/slack-build-status:dev
        workspace: estafette
        channels:
        - '#build-status'
        when:
          status == 'succeeded' ||
          status == 'failed'