builder:
  track: dev

labels:
  app: estafette-ci-web
  app-group: estafette-ci
  team: estafette-team
  language: nodejs

version:
  semver:
    major: 0
    minor: 1
    patch: '{{auto}}'
    labelTemplate: '{{branch}}'
    releaseBranch: master

stages:
  restore:
    image: node:10.9.0-alpine
    commands:
    - npm install

  unit-test:
    image: node:10.9.0-alpine
    commands:
    - npm run unit

  build:
    image: node:10.9.0-alpine
    commands:
    - npm run build

  bake:
    image: extensions/docker:dev
    action: build
    repositories:
    - estafette
    path: ./publish
    copy:
    - dist
    - nginx.vh.default.conf

  push-to-docker-hub:
    image: extensions/docker:dev
    action: push
    repositories:
    - estafette

  slack-notify:
    image: extensions/slack-build-status:dev
    webhook: estafette.secret(VQhyeydGURZSFLmh.zxAW1ZVhI7JqLgr9-K7_YuzSFWAasNFRIHAm9OXj2RK_Wa-FWXt9LCCJuD6K6jz_SYpbEhiBWcjd0VkD23AazyLmz3EsImi2C1AJ82ltxuMmN93rPZbdP3kT5vwa)
    channels:
    - '#build-status'
    when:
      status == 'failed'

releases:
  tooling:
    stages:
      deploy:
        image: extensions/gke:dev
        namespace: estafette
        visibility: iap
        container:
          port: 8080
          cpu:
            request: 10m
            limit: 200m
          memory:
            request: 15Mi
            limit: 512Mi
          liveness:
            path: /robots.txt
          readiness:
            path: /robots.txt
          metrics:
            scrape: false
        hosts:
        - estafette.secret(z6C9Piz4EhMxWMc8.uxcITmg39HiLJuuqSyPRM06PTWNd6S1x1QxfYYeyGoBLcgkM)
        resilient: true
        dryrun: true