builder:
  track: dev
  medium: memory

labels:
  type: web
  app-group: estafette-ci
  team: estafette-team
  language: nodejs

version:
  semver:
    major: 1
    minor: 0
    patch: 0
    labelTemplate: '{{branch}}-{{auto}}'
    releaseBranch: 1.0.0

stages:
  audit-and-restore:
    parallelStages:
      snyk:
        image: extensions/snyk:dev
        severity-threshold: medium

      audit:
        image: extensions/npm-audit:dev
        action: audit
        level: low
        dev-level: moderate
        workspace: estafette
        channels:
        - '#npm-audit'

      restore:
        image: node:15-alpine
        commands:
        - npm ci

  lint-and-build:
    parallelStages:
      lint:
        image: node:15-alpine
        commands:
        - npm run lint

      build:
        image: node:15-alpine
        commands:
        - npm run build

      lint-helm-chart:
        image: extensions/helm:dev
        action: lint

      package-helm-chart:
        image: extensions/helm:dev
        action: package

  bake:
    image: extensions/docker:dev
    action: build
    repositories:
    - estafette
    path: ./dist
    copy:
    - favicon.ico
    - nginx.vh.default.conf
    - docker-entrypoint.sh
    - package-lock.json

  check-container:
    parallelStages:
      check-efficiency:
        image: extensions/docker:dev
        action: dive
        repositories:
        - estafette

      # incorrectly flags a vulnerability (see https://github.com/nginxinc/docker-nginx/issues/429), disabling for now
      # vulnerability-scan:
      #   image: extensions/docker:dev
      #   action: trivy
      #   repositories:
      #   - estafette

  test:
    services:
    - name: ci.estafette.io
      image: estafette/estafette-ci-web:${ESTAFETTE_BUILD_VERSION}
      readiness:
        path: /robots.txt
        port: 5000

    image: node:15-alpine
    commands:
    - apk add curl
    - curl --fail http://ci.estafette.io:5000/manifest/encrypt

  push-to-docker-hub:
    image: extensions/docker:dev
    retries: 5
    action: push
    repositories:
    - estafette

  test-helm-chart:
    services:
    - name: kubernetes
      image: bsycorp/kind:latest-1.19
      readiness:
        path: /kubernetes-ready
        port: 10080
        timeoutSeconds: 120
    image: extensions/helm:dev
    action: test
    values: |-
      extraLabels:
        team: estafette

      extraSecrets:
      - key: gcp
        annotations: {}
        mountPath: /gcp
        data:
          service-account-key.json: |
            {}

      extraConfigmaps:
      - key: templates
        annotations: {}
        mountPath: /templates
        data: |
          manifest-docker.tmpl: |
            labels:
              container: {{.ContainerName}}
              team: {{.TeamName}}
              language: docker

            stages:
              bake:
                image: extensions/docker:stable
                action: build
                repositories:
                - estafette

              push-to-docker-registry:
                image: extensions/docker:stable
                action: push
                repositories:
                - estafette

  clone-charts-repo:
    image: extensions/git-clone:dev
    repo: helm-charts
    branch: main

  publish-helm-chart:
    image: extensions/helm:dev
    action: publish
    repoBranch: main

  slack-notify:
    image: extensions/slack-build-status:dev
    workspace: estafette
    channels:
    - '#build-status'
    when:
      status == 'succeeded' ||
      status == 'failed'

releases:
  tooling-estafette:
    actions:
    - name: deploy-simple
    - name: restart-simple
      hideBadge: true
    clone: true
    stages:
      deploy:
        image: extensions/gke:dev
        namespace: estafette-ci
        strategytype: AtomicUpdate
        visibility: iap
        iapOauthClientID: estafette.secret(iXOTyaK0CMquct2i.gHSRFMIopefYNe0bG4fANPaRaBknLwPP4qa1KiIUR_UWW6ORO5n9rLKvKGeRg5U_c_D3gQipezDEzmfaO7jsLbk8f8GpV4JFqMy3hT8g0dkdr5ndOkAwblORXBvK482HY7ihEWhEuRtyzGpK9YGALA==.qUmsBfkw3v36MosJJrfGZ9-yc09RHUjB55e4bAw5KPscGJ6eOLv-GTDQmVvuPK1x5NyJqrc=)
        iapOauthClientSecret: estafette.secret(UwPXjVCad4ycIYJK.SSTHl16_SNYh4p0JB5o-nDdAnhQM3gKLgLmapXhj4fGQT0zgkQMLP-TVp18jyWFW.YxXxmUntMPgvyMI_JtxuzB18qEBw_gnOhImTolZTnuDveWlHDvG5nrmRJnjMd5xb1coCBsw=)
        imagePullSecretUser: estafette.secret(iydnJgQZLGpU33At.mZSQ1dw1Sqk_YcjZuyPs4kg4Fg5h4yS1m5T36ckDrg==.io-Fy8AvB6MyeY7QrDL_Hp537Sie9BHHFhs_2wZV6AFSj9vjBV82ivLJJqhoxrvnRB-zyl8=)
        imagePullSecretPassword: estafette.secret(uDVlBea75D_GCVdF.89h0siWMpyr6mVvHyQzKFtV6QgbipxfR8_8IjJNUimopr5RntNgLxCyTyMKguu2e.3oUzkAq_yjvFtkaa3QifF4NjUBCXsgfL2MoYsr5QnkHkpGDcxWIePRsSI8h9Ye3lK33dW4o=)
        container:
          repository: estafette
          cpu:
            request: 10m
          memory:
            request: 15Mi
            limit: 512Mi
          liveness:
            path: /robots.txt
          readiness:
            path: /robots.txt
          metrics:
            scrape: false
        hosts:
        - estafette.secret(1Q0TpnxVNRBT-Ef5.wMLGlenN2F_oZl-vPNvMfur_geiDicdkmsuyumPWMzntP1hf.wtjGnPrKgkjiJQS4LtnEYKHomuCoauYsurqd9mWpqV3O3oPFd3QpqLNjhoJA4d7CYV9snJU=)
        - estafette.secret(Yckgy_NXzit9gA2t.l8LZcWPZbKkf5fMydVx6beetqZ_5sINemOrovXxfv0IbUmETD2TE.ldjZeHDeNr4Vpb8-KFxpavSwpdS1up1EbF1RNaa5S0SJ23IeCp9OQWfCjvf-ceIgFv8pwyg=)
        chaosproof: true
        manifests:
          files:
          - gke/ingress.yaml

      slack-notify:
        image: extensions/slack-build-status:dev
        workspace: estafette
        channels:
        - '#build-status'
        when:
          status == 'succeeded' ||
          status == 'failed'