builder:
  track: dev

labels:
  app-group: estafette-ci
  team: estafette-team
  language: nodejs

version:
  semver:
    major: 0
    minor: 1

stages:
  audit:
    image: extensions/npm-audit:dev
    action: audit
    workspace: estafette
    channels:
    - '#npm-audit'

  restore:
    image: node:11.15.0-alpine
    commands:
    - npm ci

  lint:
    image: node:11.15.0-alpine
    commands:
    - npm run lint

  build:
    image: node:11.15.0-alpine
    commands:
    - npm run build

  upload-to-gcs-bucket:
    image: extensions/gcs:dev
    credentials: gke-tooling
    action: copy
    bucket: estafette.secret(8uUO_ASSO694bx59.R4QPJTVZYxrjZpR6f-x3MVxDfL8ggG728kOSewVEwFslM4GR3cjz)
    source: 'dist/*'
    destination: ${ESTAFETTE_BUILD_VERSION}/
    # defaults
    recursive: true
    compress: true
    parallel: true

  bake:
    image: extensions/docker:dev
    action: build
    repositories:
    - estafette
    path: ./dist
    copy:
    - favicon.ico
    - nginx.vh.default.conf
    - docker-entrypoint.sh

  push-to-docker-hub:
    image: extensions/docker:dev
    retries: 5
    action: push
    repositories:
    - estafette

  slack-notify:
    image: extensions/slack-build-status:dev
    workspace: estafette
    channels:
    - '#build-status'
    when:
      status == 'succeeded' ||
      status == 'failed'

releases:
  tooling:
    clone: true
    stages:
      deploy:
        image: extensions/gke:dev
        namespace: estafette
        visibility: iap
        container:
          repository: estafette
          cpu:
            request: 10m
            limit: 200m
          memory:
            request: 15Mi
            limit: 512Mi
          liveness:
            path: /robots.txt
          readiness:
            path: /robots.txt
          metrics:
            scrape: false
        hosts:
        - estafette.secret(z6C9Piz4EhMxWMc8.uxcITmg39HiLJuuqSyPRM06PTWNd6S1x1QxfYYeyGoBLcgkM)
        chaosproof: true
        manifests:
          files:
          - gke/ingress.yaml

      slack-notify:
        image: extensions/slack-build-status:dev
        workspace: estafette
        channels:
        - '#build-status'
        when:
          status == 'succeeded' ||
          status == 'failed'