builder:
  track: dev

labels:
  app: estafette-ci-web
  app-group: estafette-ci
  team: estafette-team
  language: nodejs

version:
  semver:
    major: 0
    minor: 1
    patch: '{{auto}}'
    labelTemplate: '{{branch}}'
    releaseBranch: master

env:
  GCR_PROJECT: estafette.secret(3tHZ9bT_wEz5K8Cx.kZyD5m8L-7-zpvzZ4bkeyUdKLiGfRx_ttoY=)

stages:
  restore:
    image: node:10.9.0-alpine
    commands:
    - npm install

  unit-test:
    image: node:10.9.0-alpine
    commands:
    - npm run unit

  build:
    image: node:10.9.0-alpine
    commands:
    - npm run build

  bake:
    image: extensions/docker:dev
    action: build
    repositories:
    - estafette
    path: ./publish
    copy:
    - Dockerfile
    - dist
    - nginx.vh.default.conf

  push-to-docker-hub:
    image: extensions/docker:dev
    action: push
    repositories:
    - estafette

  slack-notify:
    image: extensions/slack-build-status:dev
    webhook: estafette.secret(VQhyeydGURZSFLmh.zxAW1ZVhI7JqLgr9-K7_YuzSFWAasNFRIHAm9OXj2RK_Wa-FWXt9LCCJuD6K6jz_SYpbEhiBWcjd0VkD23AazyLmz3EsImi2C1AJ82ltxuMmN93rPZbdP3kT5vwa)
    channels:
    - '#build-status'
    when:
      status == 'failed'

releases:
  tooling:
    stages:
      git-clone:
        image: extensions/git-clone:dev

      deploy:
        image: extensions/gke:dev
        env:
          GCLOUD_KEY_FILE: estafette.secret(DkhP7YHibRM3H5_L.Q0klhtaw1rWf_IxtdAeZG7MAMHHINDvW_3cLBapY-o-q2HYLKvTqmUHF9Ka5F00DPQkVg5XAsfU3Kld4rtjr2cUvWUvoaMhahapUK0wLHFggOjAoTs6CDvzuv1MczcpLVrJnc9_GCXTnmBy5v4hcu9EXAT7nDwlpZCbIIqaZIbDbIxh7lphJ7CoN3yGxSb7UVKHbYo3ViPX6YCkA6ijxc4qAWNjasqAAUv-C_U1mM1FrcvNoaZ7Fr5W_22Yd5K7gK3qi_q3HfvQYL6oBjiVu163ujSSwJBnNxgJguktFiFknl2w8XS064OjqWP4exq6LBCTJXF6keKOPdo6ulG7IkVA0ohPZKBhZgY-y96ZFjZleJeO0U5W1kI-JV0MvwYJFVU-asLjh_09MLFN12_gF2yKXp8hXvANCrVg2ofX_dbYzJcEaXlLJbZZ0yjV6ZErx9QGrZOz4UpW_qYj8OxnNZCCdv0Lv61reJteRziGLKV9N8t1FadQOi4rog4Iw-S-TVAHIB5RfKuqO5ovEEoreN10cCn8mE2gZFP2tURs0q5ZkMYK5BadDz-zgc6AkE0oDVm9zvEAlwNAF8ANevw-oGjgQfwXy-HV6Jl3_-DkXGtTxEjEmZmVV-rtAsbxAvCpdrRpLAhVFo9Mst2wgKmt0dKfcUFUNrGAOq__TiCV2ijCfDFTzxVTJKOLVzVnkk-p0cHRscXDZ-fKyX9IJcSIm0UjbTMhjiEIEJPJBPfVAlnKmLDkQy0vKp61BqhFenThfj8i4HltUE3G2vP8rGGmZTkimz0DGVRQxK3IUsxxXg2S5C2TU5Ic1XSPGo4wfpb0goo0PBua3tAjvYVuFdEh_JccFfE_Okh1Tu7NBEdgukGs20OGudDot_SeZEqkjEJyKie9hZIInqMGsc1tgCGntvctvRA8AC6BzdzaaqgAzxt2aGzPqedfcI368e77fRxXbzFTt8pL865VcxM2fZ4rYDO5sVioa41LGsjCQRoek_uNA9JXuTDpPIi3WK5WozcmVzFdPXzE5fG7rxP4CMRFw3hZ7OCqVwDj7UqFd1jirUKAm90bc3hb_SW3F1E6elS1oVXob4Bz7hdg8Y-P9psdY2OxUGRO3No3PldQ6V4OIM9n7uECbO8m4etuskgPk5f7V_q-JO9-HAGUPLFcBxEgQ8TwDfc5NmZSRUERNFt_3fSTOfpq38IgM3184HEjV57fTHvhy7VD-9T3sjlrtWavJScMKzWrJk0qufW-7_mircIKJE0nMqCyxWPgoXI7cHWgk_oAk5B1wOD74XGGYAzE--LwB2omoN1UjcWZgT1JlDWNd19p16bZspR-B1OeYBdPozhbPM637jQovFk3RXSdxLLsR99VtAJAKfL8-zCVrLROZrlvPmFTAunrZiNvjSTkPcjinGHF5PAYHNhn9iQPpM0KzL_AHuFG8DWJL_W0luDMnQktUWy-8IQ2sVqm-bIyvtDF9PGSTQHNVoTsmHhuM0FIfve19fy06OuQg-gf7pIyyHPvxPNoPvSnAIE0OCHkJqnLnlIBk3b8dG7dD5r_pWiYMtNIJtcwAIrJUmsC0U8OjX3BIfIt5-go2CwhnpqIZBT4ZrzhQ5d49j4Y0-e095sqWT9rqDlX8ogo7ZC0lOtHGYgOYVWndCg9SVLsLhSLYbI5xnQ9727JKr4EuoWL8gAfimLMzhkbugvGUwaHa6m2d6aVSfk9DNSxb7t7htiNndym63NtADaQC9yE1GnW3hHt-otH2C9n4e6AGprpx_x6S5gvFWmWEfAHWibTwIr-RdXm9HHlFJsh198db_G79Y1wmzASlIjwZ8bSeWTIzkcmlafODF-KY0TRhfICno3RnTzSdkJeIRLGycR2TvMM1wLrYi5bguvrPSYYpesXuOiI1AlW7-TbkHFyQ22nIZw1r_95oUKezVWGjmcwBNYANkjRpf0ae-Eact9iH6QWqf80Wx_dLY0nY-sZUSG35Gnf1HFQz_ZJSfl52UQTSwZp3d79X3hmBAnIlWivAt6IDmzhZ_qOAlOWyRxC95sJiN2eoUqMgwrEeqrobxQGrR6x9bQq61B-sXFGPGDmooSJc8a26bX3XrAFEKC3EMYoPppGupR3e-hI3FZdJGlcIvaj-dON1tVhS6VsTCfFOsf6HKkdUilkacvQBGLNUl4F3O4zpG66oDIi1_9fN0WZRkE_wLYw-bP79mKQht2r6IeJsIxx7J2t8WoN_kDmGcJc0kpTuX7urVZ4aBQ_1Sdj89wK1zMnoxxBSe4scNUwIvr4F1rH8MvVBTIJMyTxm2Dj5vm9cgUx9vn5hrRcbkpE0k_SbyBl0KBeR_8OArRAvawHUuyPFWJ3b-tVG5M5z48npIwbCVLChp7vjEHs5-Cxc5Bb0ezKmjksrhFIde3Nn2PVc9L6Ii25BcmXUUi6ngG3m21Z61o3AJ0wopC7dvJt2P6M8o3OiNa_V4myNByJi7rzHze36B2qEyzsifExTntzJLTSwsir4CNnei784o-cx5-Vu_oxDLmbi80WxWupk74ovoqkKEoWk39rVR67yvBCzgEHs0k7rWMksNIq-l0HMmL6EtkiHleWbb4LoIlULpMSeJWJiM8fmcXKIsFBJHwABkIsUTo0mEgJtmnGhoqY3MdHVfxaaQ9xM6TVn91MCI5U1i0bQeOAWpmeXupdF3Phwo8fcQriM5avqHaLqrr4uXwYkG5iRn5gxDLQU9EfHJuJx2gdd0hIj3aTrYTLbwF5XySgmGu5VpI5Qmr9mgFLy6wzWXHTFeLeZjtDfXwc8T32YvoVGsn_rSTJb8Y8DOQKi-QB0aqBLV0gbQfnbB__IxXOdJBFtmroj7nE3jLOaREuXemv7cfBua4Qf02dK-n7Ba2JWU2_i7WC_TwtbUBIGIFfKMPgvhozQdqUK-WOjxApNjGTN4mJApKWQiEGZYEmP3KWQ25tXwEIFJ1i13Ni1xp2l7kn96XT3R4h0wdk0atx2W3AXW5-ktXdWG0R8E-5lrkZ7O8VcIU8rcmoLCLz0yARQQhm1ULDCVmpKc3dN98zEGSqxKPUjFopTcXPtgTGk-KIBf3YOFW_1VqHXobQt31sycRVhKNuKNYhJpEQkOZz7VHZ0yJDsgmJ2OG2lbbZ74KaoQZV2PXTfFvqPgEFts6zg3bG4l0j2druVdcH8CK-WfVQn9zO9pTU10YtN0CtsbcPXWTrfGYoE1sTxDmKVR5DJZRfKGEnS-MkgKKUVQJuGaxznwaSMRw0MgR8NQlxUOruM7CV6yVVMmIsf5zuKQg9X1tOg514sqQeBYz-n9Z7mKsZAs1AZSe4rY60sOOQpHrjelkw-YDrPHFYFTYIRFQCV_vQ9Gja9Pfdblh088ogqSYU10rWeRDOEXQSl__eSpScb9GX8ctu6n70Hm_lZxqDABsIzkIEutekGy4WH6rP3e7k1ig_CgnioNqSTBImeWI38GdRjPBXNdNUVWY2zzge7tSGEDrlsliVY9I4HI8FdZ4aizrq8AThhYnfOqbDdAucQ_c_cT0N04xLtMELLvt5dXzXL9_-Ah2bfTObLVitRmtpYOD1Yfw7-iWEbvFTd60rzK2pjtRy4OnI2qOQ2VYwEH2GhwYFMFtTOLapkyQRpyJjwrtFMXlCGzacszNEO9U4ocFfS1994TgsCGTQbB9Tjkm5m28jK4JcWE3ziLavWrn1LUoCOGqx9fJYmQpBpPFlFCa03jyKO2Xyo5ekNvOHi8ud3HQf0wMw-QQ1265SwaQSuqqnIzw216kJG55fcVeSJvpVwjoNpvTV8mInYrdzlmQFnZzJMIHsFsngRbFfPY0-f5I4NG9ti6Qy4BCq64YHoWQVHPYfiac05TuM5SFMDPEjipqT9P8EsaYXYXPEZz3YQrTrsWKLaL2D7OjUsk64VbO4CE1RH6OIa8IK-_g_IN5toCHnZ5V18K7askGCoDk2mSdDPjC9kvhhXhmevfMMKAQTJupJnzUVy4Y2jJfFuSTj68Zr6yGXSo9adwxvf9VqYEVurTYLNuwrtyAC9x-0FFfCn5lsmrNPXBlvUilNW9vm1qt78Sr2kPsWJIcx6gNQ94TLKa3WUJHOhHu976xNEUElJtoT4gEbs3zfKjVZTd1MWi2khTqV1MJAM6GwMvtNcYM8j8N0HNzDPvf9Xeast9rRvtWDNZ7X1xvHw6_pIaEicgwcvGv9fOfXUEz8P4Bfk4ogs7cof_OjPlj7rkoLAk0QGBnBMesKoKpHfGU6gPA==)
          GCLOUD_SA_NAME: estafette.secret(dTj9MkqIHLqM7rVU.O6Enzm0A5USM43aAJ9zWmYe5L8f9HXSMjQACck24DcUtFylL0c0tkE723IXLjkcwMecin_kSg16ok1U6_uYEynOagxzGoQ_WcqfanT_7zBtSPxPgEPRO)
          GCLOUD_PROJECT_NAME: estafette.secret(BmdGMBT2lalsPp7Q.uLx3rQPGO4snBlRDcUh2hQB76TRfREvGZcYQzUK2QVVOtQEueZQ=)
          GCLOUD_GKE_CLUSTER_NAME: estafette.secret(tgsulzRvtjkXoHWT.LMn2jrcnGwRWLLk6vZUV7AqenVuU3EI=)
          GCLOUD_GKE_ZONE: estafette.secret(WrjS-oxlbTqMprdg.kdlCnbAW4bFkE6cQw-16jMddBe7WY3NBb9uIZh5g)
          CPU_REQUEST: 10m
          CPU_LIMIT: 200m
          MEMORY_REQUEST: 15Mi
          MEMORY_LIMIT: 512Mi
          HOSTNAMES: estafette.secret(z6C9Piz4EhMxWMc8.uxcITmg39HiLJuuqSyPRM06PTWNd6S1x1QxfYYeyGoBLcgkM)
        shell: /bin/bash
        commands:
        - echo "${GCLOUD_KEY_FILE}" | base64 -d > key-file.json
        - gcloud auth activate-service-account ${GCLOUD_SA_NAME} --key-file ./key-file.json
        - gcloud config set account ${GCLOUD_SA_NAME}
        - gcloud config set project ${GCLOUD_PROJECT_NAME}
        - gcloud container clusters get-credentials ${GCLOUD_GKE_CLUSTER_NAME} --zone ${GCLOUD_GKE_ZONE}
        - cat kubernetes.yaml | envsubst | kubectl apply -f -
        - kubectl rollout status deploy/estafette-ci-web -n estafette