{{- range .Values.extraConfigmaps -}}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "estafette-ci-web.fullname" . }}.{{ .key }}
  labels:
    {{- include "estafette-ci-web.labels" . | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 -}}
  {{- end }}
{{- with .data }}
data:
  {{- tpl . $ | nindent 2 }}
{{- end }}
{{- end }}