apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "estafette-ci-web.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "estafette-ci-web.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "estafette-ci-web.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}