apiVersion: v1
kind: Service
metadata:
  name: {{ include "estafette-ci-web.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "estafette-ci-web.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if .Values.openresty.enabled }}
      targetPort: https
      {{- else }}
      targetPort: web
      {{- end }}
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: {{ include "estafette-ci-web.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
